version: 0.9.0
project:
  name: ai-trackdown-pytools
  description: ''
  version: 0.9.0
editor:
  default: vim
templates:
  directory: templates
tasks:
  directory: tasks
  auto_id: true
  id_format: TSK-{counter:04d}
git:
  auto_commit: false
  commit_prefix: '[ai-trackdown]'
plugins: {}
issues:
  counter: 13
prs:
  counter: 11
epics:
  counter: 11
